version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-ima-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ac123456
      POSTGRES_DB: my_ima
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
